### ISSUE TITLE
[FEATURE REQUEST] There is now an official swift async algorithms package.

### ISSUE THREAD

**Issue by BrentMifsud** [AsyncCommunity/AsyncExtensions#18]
It might be worth while contributing some of the features of this library over there.

https://github.com/apple/swift-async-algorithms

**Comment by twittemb** [comment]
Hi @BrentMifsud 

Yep, I've already posted some comments there -> https://forums.swift.org/c/related-projects/swift-async-algorithms/86

and will try to propose Implementations for operators that do not already exist in their repo.
