### ISSUE TITLE
[BUG] AsyncCurrentValueStream `element` is not public

### ISSUE THREAD

**Issue by Prince2k3** [AsyncCommunity/AsyncExtensions#4]
Unable to use property `element`. It isn't public

**To Reproduce**
1. use AsyncStreams.CurrentValue
2. attempt to print(currentValue.element)
3. See build error

```Swift 
let currentValue = AsyncStreams.CurrentValue<Int>(1)

Task {
    for try await element in currentValue {
        print(element) 
    }
}

print(currentValue.element)  // error will occur
```
**Expected behavior**
Expect that `element` is accessible 

**Environment:**
 - 0.1.0

**Comment by twittemb** [comment]
resolved by https://github.com/AsyncCommunity/AsyncExtensions/pull/5.
Thanks.
